import { PlantStation, SafetyOfficerLocation } from '../types';

export const PLANT_STATIONS: PlantStation[] = [
  {
    id: 'station_refinery',
    name: 'وحدة التكرير ومعالجة الغاز الطبيعي',
    nameAr: 'محطة التكرير ومعالجة الغاز الطبيعي',
    type: 'منطقة صناعية حرجة',
    typeAr: 'منطقة صناعية حرجة (Zone 1 - ATEX)',
    zoneCode: 'ST-01',
    riskLevel: 'critical',
    activeIncidents: 2,
    coords: { x: 26, y: 38, lat: 24.6879, lng: 46.7223 },
    descriptionAr: 'مجمع التكرير عالي الضغط، أبراج التقطير ووحدات استرجاع الكبريت وخزانات الهيدروكربونات الثقيلة.',
    descriptionEn: 'مجمع التكرير عالي الضغط، أبراج التقطير ووحدات استرجاع الكبريت وخزانات الهيدروكربونات الثقيلة.',
    safetyOfficerIds: ['officer_khalid', 'officer_sarah']
  },
  {
    id: 'station_substation',
    name: 'محطة المحولات الكهربائية الرئيسية 132 ك.ف',
    nameAr: 'محطة المحولات الكهربائية الرئيسية 132 ك.ف',
    type: 'جهد كهربائي فائق',
    typeAr: 'جهد كهربائي فائق وحماية LOTO',
    zoneCode: 'ST-02',
    riskLevel: 'high',
    activeIncidents: 1,
    coords: { x: 72, y: 28, lat: 24.6888, lng: 46.7261 },
    descriptionAr: 'قواطع الدوائر الرئيسية، محولات الجهد العالي، خطوط التغذية الهوائية وغرف التحكم بالعوازل الغازية GIS.',
    descriptionEn: 'قواطع الدوائر الرئيسية، محولات الجهد العالي، خطوط التغذية الهوائية وغرف التحكم بالعوازل الغازية GIS.',
    safetyOfficerIds: ['officer_faisal']
  },
  {
    id: 'station_marine',
    name: 'رصيف الشحن والتصدير البحري',
    nameAr: 'رصيف الشحن والتصدير البحري',
    type: 'منطقة بحرية ومرفأ',
    typeAr: 'أرصفة التحميل وأذرع الشحن البحرية',
    zoneCode: 'ST-03',
    riskLevel: 'medium',
    activeIncidents: 0,
    coords: { x: 84, y: 65, lat: 24.6845, lng: 46.7305 },
    descriptionAr: 'أرصفة إرساء ناقلات النفط والغاز، أذرع التحميل الهيدروليكية، وأنظمة المكافحة المائية الرغوية العائمة.',
    descriptionEn: 'أرصفة إرساء ناقلات النفط والغاز، أذرع التحميل الهيدروليكية، وأنظمة المكافحة المائية الرغوية العائمة.',
    safetyOfficerIds: ['officer_maryam']
  },
  {
    id: 'station_workshop',
    name: 'ورشة الصيانة الميكانيكية والهيدروليكية المركزية',
    nameAr: 'ورشة الصيانة الميكانيكية والهيدروليكية المركزية',
    type: 'ورش صناعية ثقيلة',
    typeAr: 'ورش التجهيز والرافعات الجسرية',
    zoneCode: 'ST-04',
    riskLevel: 'medium',
    activeIncidents: 1,
    coords: { x: 41, y: 70, lat: 24.6838, lng: 46.7235 },
    descriptionAr: 'مكائن الخراطة، الرافعات العلوية سعة 50 طناً، اختبارات الضغط الهيدروستاتيكي، وعمليات اللحام بالقوس الكهربائي.',
    descriptionEn: 'مكائن الخراطة، الرافعات العلوية سعة 50 طناً، اختبارات الضغط الهيدروستاتيكي، وعمليات اللحام بالقوس الكهربائي.',
    safetyOfficerIds: ['officer_fahad']
  },
  {
    id: 'station_hazmat',
    name: 'مجمع مستودعات الكيماويات والمواد الخطرة',
    nameAr: 'مجمع مستودعات الكيماويات والمواد الخطرة',
    type: 'مستودعات كيميائية معزولة',
    typeAr: 'تخزين كيميائي وتدابير احتواء التسرب',
    zoneCode: 'ST-05',
    riskLevel: 'critical',
    activeIncidents: 2,
    coords: { x: 54, y: 46, lat: 24.6858, lng: 46.7252 },
    descriptionAr: 'خزانات الأحماض والقواعد الكيميائية، مواد المعالجة، أنظمة التهوية المقاومة للانفجار وحواجز الاحتواء الثانوية.',
    descriptionEn: 'خزانات الأحماض والقواعد الكيميائية، مواد المعالجة، أنظمة التهوية المقاومة للانفجار وحواجز الاحتواء الثانوية.',
    safetyOfficerIds: ['officer_yasser']
  },
  {
    id: 'station_ops_command',
    name: 'مركز القيادة والتحكم وإدارة الأزمات',
    nameAr: 'مركز العمليات والتحكم المركزي والطوارئ',
    type: 'مبنى القيادة والعمليات',
    typeAr: 'غرفة التحكم المركزية المحصنة (CCR)',
    zoneCode: 'ST-06',
    riskLevel: 'low',
    activeIncidents: 0,
    coords: { x: 50, y: 15, lat: 24.6895, lng: 46.7240 },
    descriptionAr: 'غرفة العمليات المركزية المحصنة، شاشات التحكم الصناعي SCADA، وغرفة إدارة الأزمات والاتصال اللاسلكي المباشر.',
    descriptionEn: 'غرفة العمليات المركزية المحصنة، شاشات التحكم الصناعي SCADA، وغرفة إدارة الأزمات والاتصال اللاسلكي المباشر.',
    safetyOfficerIds: ['officer_naif']
  }
];

export const SAFETY_OFFICERS_LOCATIONS: SafetyOfficerLocation[] = [
  {
    id: 'officer_khalid',
    name: 'م. خالد بن سلطان السويدي',
    nameAr: 'م. خالد بن سلطان السويدي',
    jobTitle: 'كبير أخصائيي الاستجابة الفورية والتدخل الوقائي السريع',
    jobTitleAr: 'كبير أخصائيي الاستجابة الفورية والتدخل الوقائي السريع',
    employeeId: 'EMP-4101',
    stationId: 'station_refinery',
    stationNameAr: 'محطة التكرير ومعالجة الغاز',
    phone: '+966 50 410 1122',
    radioChannel: 'قناة اللاسلكي VHF 01 (طوارئ وتدخل سريع)',
    status: 'responding',
    statusAr: 'معالجة فورية ذاتية مباشرة (معتمدة وفق اشتراطات السلامة)',
    statusEn: 'معالجة فورية ذاتية مباشرة',
    batteryLevel: 98,
    coords: { x: 28, y: 40, lat: 24.6879, lng: 46.7223 },
    avatar: 'خ.س',
    activeTaskId: 'REP-2026-104',
    isFastestResponder: true,
    swiftRemediationAvgMinutes: '1.8 دقيقة',
    swiftAutonomousRemediationsCount: 34,
    fastestBadgeTitleAr: 'مسؤول السلامة الأسرع في تنفيذ المعالجة الفورية دون انتظار توجيهات المدير العام وفقاً لاشتراطات ومعايير السلامة والصحة المهنية'
  },
  {
    id: 'officer_sarah',
    name: 'م. سارة بنت عبد الله المهيدب',
    nameAr: 'م. سارة بنت عبد الله المهيدب',
    jobTitle: 'مشرف أول تفتيش السلامة والامتثال الميداني',
    jobTitleAr: 'مشرف أول تفتيش السلامة والامتثال الميداني',
    employeeId: 'EMP-4105',
    stationId: 'station_refinery',
    stationNameAr: 'محطة التكرير ومعالجة الغاز',
    phone: '+966 50 410 5001',
    radioChannel: 'قناة اللاسلكي VHF 04 (عمليات المحطة)',
    status: 'on_patrol',
    statusAr: 'جولة تفتيشية لمطابقة اشتراطات السلامة',
    statusEn: 'جولة تفتيشية نشطة',
    batteryLevel: 92,
    coords: { x: 24, y: 35, lat: 24.6875, lng: 46.7220 },
    avatar: 'س.م',
    activeTaskId: 'REP-2026-101',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '3.2 دقيقة',
    swiftAutonomousRemediationsCount: 22
  },
  {
    id: 'officer_faisal',
    name: 'م. فيصل بن عبد العزيز الغامدي',
    nameAr: 'م. فيصل بن عبد العزيز الغامدي',
    jobTitle: 'أخصائي سلامة الطاقة الكهربائية وإجراءات LOTO',
    jobTitleAr: 'أخصائي سلامة الطاقة الكهربائية وإجراءات LOTO',
    employeeId: 'EMP-4112',
    stationId: 'station_substation',
    stationNameAr: 'محطة المحولات الكهربائية 132 ك.ف',
    phone: '+966 55 921 4433',
    radioChannel: 'قناة اللاسلكي VHF 03 (أمن الكهرباء)',
    status: 'on_patrol',
    statusAr: 'فحص عزل القواطع وتأريض الخطوط',
    statusEn: 'فحص دوري نشط',
    batteryLevel: 88,
    coords: { x: 72, y: 28, lat: 24.6888, lng: 46.7261 },
    avatar: 'ف.غ',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '2.9 دقيقة',
    swiftAutonomousRemediationsCount: 19
  },
  {
    id: 'officer_yasser',
    name: 'د. ياسر بن إبراهيم المنصور',
    nameAr: 'د. ياسر بن إبراهيم المنصور',
    jobTitle: 'أخصائي سلامة العمليات والمواد الكيميائية الخطرة',
    jobTitleAr: 'أخصائي سلامة العمليات والمواد الكيميائية الخطرة',
    employeeId: 'EMP-4120',
    stationId: 'station_hazmat',
    stationNameAr: 'مجمع مستودعات الكيماويات الخطرة',
    phone: '+966 54 883 2190',
    radioChannel: 'قناة اللاسلكي VHF 02 (مجمع المواد الخطرة)',
    status: 'at_station',
    statusAr: 'مراقبة مستشعرات كشف تسرب الغازات',
    statusEn: 'متواجد بالمحطة',
    batteryLevel: 99,
    coords: { x: 54, y: 46, lat: 24.6858, lng: 46.7252 },
    avatar: 'ي.م',
    activeTaskId: 'REP-2026-102',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '3.5 دقيقة',
    swiftAutonomousRemediationsCount: 15
  },
  {
    id: 'officer_fahad',
    name: 'ك. فهد بن عبد الله العتيبي',
    nameAr: 'ك. فهد بن عبد الله العتيبي',
    jobTitle: 'قائد فرقة التدخل والإنقاذ الميداني',
    jobTitleAr: 'قائد فرقة التدخل والإنقاذ الميداني',
    employeeId: 'EMP-4135',
    stationId: 'station_workshop',
    stationNameAr: 'ورشة الصيانة الميكانيكية والهيدروليكية',
    phone: '+966 50 771 9900',
    radioChannel: 'قناة اللاسلكي VHF 09 (الإنقاذ والطوارئ)',
    status: 'on_patrol',
    statusAr: 'فحص معدات الوقاية والرافعات الجسرية',
    statusEn: 'جولة تفتيش الورش',
    batteryLevel: 84,
    coords: { x: 41, y: 70, lat: 24.6838, lng: 46.7235 },
    avatar: 'ف.ع',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '2.4 دقيقة',
    swiftAutonomousRemediationsCount: 26
  },
  {
    id: 'officer_maryam',
    name: 'م. مريم بنت صالح الدوسري',
    nameAr: 'م. مريم بنت صالح الدوسري',
    jobTitle: 'مفتش أول السلامة البحرية والموانئ الصناعية',
    jobTitleAr: 'مفتش أول السلامة البحرية والموانئ الصناعية',
    employeeId: 'EMP-4148',
    stationId: 'station_marine',
    stationNameAr: 'رصيف الشحن والتصدير البحري',
    phone: '+966 56 312 8877',
    radioChannel: 'قناة اللاسلكي VHF 06 (حركة المرفأ)',
    status: 'at_station',
    statusAr: 'إشراف على تأمين إرساء ناقلة النفط',
    statusEn: 'متواجد بالرصيف البحري',
    batteryLevel: 93,
    coords: { x: 84, y: 65, lat: 24.6845, lng: 46.7305 },
    avatar: 'م.د',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '3.1 دقيقة',
    swiftAutonomousRemediationsCount: 17
  },
  {
    id: 'officer_naif',
    name: 'م. نايف بن راشد الزهراني',
    nameAr: 'م. نايف بن راشد الزهراني',
    jobTitle: 'مشرف غرفة العمليات المركزية والاتصال السريع',
    jobTitleAr: 'مشرف غرفة العمليات المركزية والاتصال السريع',
    employeeId: 'EMP-4155',
    stationId: 'station_ops_command',
    stationNameAr: 'مركز العمليات والتحكم المركزي والطوارئ',
    phone: '+966 50 119 8844',
    radioChannel: 'قناة اللاسلكي VHF 01 (القيادة والتحكم)',
    status: 'at_station',
    statusAr: 'متابعة البث الحي للبلاغات وتوجيه الفرق',
    statusEn: 'متواجد بمركز العمليات',
    batteryLevel: 100,
    coords: { x: 50, y: 15, lat: 24.6895, lng: 46.7240 },
    avatar: 'ن.ز',
    isFastestResponder: false,
    swiftRemediationAvgMinutes: '2.0 دقيقة',
    swiftAutonomousRemediationsCount: 29
  }
];

export const DEPARTMENT_GMS = [
  {
    id: 'dept_hse',
    roleKey: 'hse_director',
    title: 'مدير عام السلامة والصحة المهنية وسلامة العمليات',
    titleAr: 'مدير عام السلامة والصحة المهنية وسلامة العمليات',
    name: 'د. طارق بن عبد العزيز الحسيني',
    nameAr: 'د. طارق بن عبد العزيز الحسيني',
    channel: 'الخط الساخن لإدارة السلامة والصحة المهنية',
    channelAr: 'الخط الساخن لإدارة السلامة والصحة المهنية',
    email: 'hse.director@plant-stop.com'
  },
  {
    id: 'dept_maintenance',
    roleKey: 'other_department',
    title: 'مدير عام الإدارة الهندسية والصيانة والاعتمادية',
    titleAr: 'مدير عام الإدارة الهندسية والصيانة والاعتمادية',
    name: 'م. بدر بن محمد الشريف',
    nameAr: 'م. بدر بن محمد الشريف',
    channel: 'مكتب توجيه فرق الصيانة والورش المركزية',
    channelAr: 'مكتب توجيه فرق الصيانة والورش المركزية',
    email: 'maintenance.gm@plant-stop.com'
  },
  {
    id: 'dept_operations',
    roleKey: 'other_department',
    title: 'مدير عام إدارة العمليات والإنتاج والتشغيل',
    titleAr: 'مدير عام إدارة العمليات والإنتاج والتشغيل',
    name: 'م. نواف بن سالم الخطيب',
    nameAr: 'م. نواف بن سالم الخطيب',
    channel: 'كونسول التحكم ومتابعة خطوط الإنتاج',
    channelAr: 'كونسول التحكم ومتابعة خطوط الإنتاج',
    email: 'operations.gm@plant-stop.com'
  },
  {
    id: 'dept_supply_chain',
    roleKey: 'other_department',
    title: 'مدير عام سلاسل الإمداد والمستودعات والخدمات اللوجستية',
    titleAr: 'مدير عام سلاسل الإمداد والمستودعات والخدمات اللوجستية',
    name: 'أ. زياد بن عبد الرحمن الفرحان',
    nameAr: 'أ. زياد بن عبد الرحمن الفرحان',
    channel: 'مكتب لوجستيات المواد والمهمات والمستودعات',
    channelAr: 'مكتب لوجستيات المواد والمهمات والمستودعات',
    email: 'supplychain.gm@plant-stop.com'
  },
  {
    id: 'dept_workers',
    roleKey: 'workers',
    title: 'توجيه مباشر للعاملين في الميدان',
    titleAr: 'توجيه مباشر للعاملين في الميدان',
    name: 'قادة فرق العمل الميدانية ومجموعات الصيانة',
    nameAr: 'قادة فرق العمل الميدانية ومجموعات الصيانة',
    channel: 'نظام الإشعار المباشر للعاملين',
    channelAr: 'نظام الإشعار المباشر للعاملين',
    email: 'field.workers@plant-stop.com'
  }
];
